export type Death = 'BORDER' | 'SNAKE_COLLISION' | 'APPLE_COLLISION' | 'SELF_COLLISION' | 'DECONNEXION';

export const Death = {
    BORDER: 'BORDER',
    SNAKE_COLLISION: 'SNAKE_COLLISION',
    APPLE_COLLISION: 'APPLE_COLLISION',
    SELF_COLLISION: 'SELF_COLLISION',
    DECONNEXION: 'DECONNEXION'
} as const;
